ALTER SESSION SET CONTAINER = XEPDB1;
SHOW CON_NAME;

/* Creación de un tablespace */
CREATE TABLESPACE tabla_grupob
DATAFILE 'tablagrupob.dbf' 
SIZE 500M 
AUTOEXTEND ON 
NEXT 1G 
MAXSIZE UNLIMITED;

/* Creación de un usuario principal */
CREATE USER grupob IDENTIFIED BY administracion 
DEFAULT TABLESPACE tabla_grupob 
TEMPORARY TABLESPACE temp;

/* Asignación de privilegios al usuario principal */
GRANT DBA TO grupob;

/* Creación de 10 usuarios con roles de consulta/actualización */
BEGIN
    FOR i IN 1..10 LOOP
        EXECUTE IMMEDIATE 'CREATE USER administradores' || i || ' IDENTIFIED BY contrasena' || i;
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO usuario' || i;
    END LOOP;
END;
/

-- Creación de tablas para el sistema de ventas y facturas

-- Tabla de Clientes
CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    direccion VARCHAR2(255),
    telefono VARCHAR2(15)
);

-- Tabla de Productos
CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    precio NUMBER(10, 2),
    stock NUMBER
);

-- Tabla de Ventas
CREATE TABLE ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER REFERENCES clientes(id_cliente),
    fecha_venta DATE,
    total NUMBER(10, 2)
);

-- Tabla de Detalle de Ventas
CREATE TABLE detalle_venta (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER REFERENCES ventas(id_venta),
    id_producto NUMBER REFERENCES productos(id_producto),
    cantidad NUMBER,
    precio_unitario NUMBER(10, 2)
);

/--------------------PARAMETRIZACIONES----------------/
-- Consultar la estructura de las tablas
SELECT table_name, column_name, data_type 
FROM user_tab_columns 
WHERE table_name IN ('CLIENTES', 'PRODUCTOS', 'VENTAS', 'DETALLE_VENTA');

-- Consultar los usuarios creados
SELECT username 
FROM all_users 
WHERE username LIKE 'ADMINISTRADORES%';
/-------------------------CONSULTAS AVANZADAS---------------/